version: '2'
services:

  data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
  dbpostgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: sous_test_template
