sudo: required
services:
- docker
language: go
go:
- 1.7.3
before_install:
- bin/ci-setup
install:
- "./bin/vendor-check"
- "./bin/check-gofmt"
- export SOUS_QA_DESC=${TRAVIS_BUILD_DIR}/${SOUS_QA_DESC}
- sous_qa_setup --compose-dir ./integration/test-registry/ --out-path=$SOUS_QA_DESC
script:
- "./bin/test-until-success 3"
- "./bin/cover"
after_success:
- bin/codecov -f /tmp/sous-cover/count_merged.txt
env:
  global:
  - SOUS_QA_DESC=qa_desc.json
  - GIT_AUTHOR_NAME=SousCI
  - GIT_COMMITTER_NAME=SousCI
  - GIT_AUTHOR_EMAIL=sous@nowhere.in.particular.com
  - GIT_COMMITTER_EMAIL=sous@nowhere.in.particular.com
  - DOCKER_VERSION=1.10.1-0~trusty
  - DOCKER_COMPOSE_VERSION=1.6.0
  - secure: jQv4im3Imakryl54Z7qR2BEa1+Gq//sAwo3XP/1J6sSdtBjtOYY1SgdAYh7pVB111HV546vKPJqQ6GsAtHM7tjnVjlF1PabAHEWl/ZP3ZXj3SvuFNaV5j5PmrJvxPlK7nbr0uG6PPspxFkZg+X87GGIyFGCp7F3EWKIU6aX6rEeBbY/greAxISmtGYHrDwK4sQnMXl4+WoagbKwoi16fK94XweU2Etg40rLwtYRdRJTPMdhrinkkkfQ4Jga5uepsmkZFjgZJySgyEzxvVuUuEYHaQreRLHzJBjPXw96tQOGpw4OT5aRJjga6PlEJRp68pC3KPrzW7lQQMMCHpxrauEqR1r1ltg+UD2GIixAT80duOl7mD6aPyx3L04L/bg4u1sI26JyHN34X/mpg9OufE47zSOC48RicSA6y4D+ZyD/dubu626NScnLufAveWaVH/mu5brVZ3ni+8BgVqDW/vfIJTyELegz7DD9wS/xaoUVnAjnTH73efce8bDAaAOvpa4dlkZEcBDU2LjasP735FNh0/sLeVsuwhopMIKPsnpwce1Fxg83ls+KRDqXj8/l67Db5nQqTvsWk3S12nvrgPO1uX/we8fqwUKuLNlnU3befd7KugvUamixGoxlX65etwt4hvFWT11Qfv/IB7JXjLToUAfXm/QpiprEm/VqZWTM=
  - secure: yoQHrMJeCnRumhKPRCvygeNUO8lHksOKfua5JZ69UwqIspfQlf27OrVJeJSqhFkpgUU9Xpo7m919RylLI9rHUaZDWGR3/S3/aoYfsmCZi8D5GJq4EsAhZba76LIEaYCJAueVX2RyHcSGVZQFoqp4V7AXwAO2yNVVdpgq4BaAauhvqU8BuCq0j/PVCGS2puossR/IO/KvBkzAaEuE+wr0MKzEEvhWDFfx61X5yDAp3U5e3sGJQzn3P8tqLSDLFLevYSevrjq4JxhOeDedGRPwdkf1RnMS5qq0W7aQ8aFQi4iE0GBFYNlFVE09oFA66HzJVwm1lf4bmqdMSJg8oDtP8XsOYltkiuUih1WRSvO+ZHuIHte9InWM4+jZh8VKO1othr+nVUMHapNq2EuZs+c7ELeOMFiCBpyWhTNoHn85F887rhaKUd6lnePuasErAAb4b7kZO+wVdkMcBE5yU6WKVTUIdOzcbqK9AXL2zia5KyttnFXqCbv3/z+k/t4AfxEr8sor+R2dPzB9W6CL0QMk3Bx7Hq6smtP6u2FWpH4wwu6TEfmnEifjErmWTBdDFscGFV4MLHI30KEWlu2bezbIKuFeKFBEi3hfabafdZsxpNh5NapVOX84J0xkDxFIKatj/RdhUyp0yPd1QczESfgWeoq1Xpw21scQh0Xk84NYAbc=
before_deploy: go get github.com/karalabe/xgo && make release
deploy:
  provider: releases
  api_key:
    secure: Nm4wGpltWerwmkUp2PrzDE6/EwRb4AZk4riuROmEVSujOnfPojbHikgaFZzOF1rryY22+RXg8HrnsldWLHmVwXOWPUTEXK8FCdaVplf+3zbV2CLQZMrrv2PQIMS7NfE6NdLLScCsyXIO13JyygLgXB7rHV3RBtXrZhjYbB2GHk6N8YMIpGfD8K1k/Rp7T/4kS2vG4U1LM86h5QFk9pkOThWroxxdKbNWOYiMCIbzMt5f8Rgn7uoyBrSr8SAc2Kutku0W2PUN4QxCAuqYPf+quaPhGDWJ3BEDCFTk2nXrZTIJr+2/KCpgrJZdG2EertzjrkwIs5gc1ltS7G8ubC5dqA+Nb5foDOt9zvPzvrwAkoGof/2pza3dpUIkTeri2kYY7hbPuWwNsGwc4tFj2LIg22vgfu5TUIZ3kaQ5fMjFAQQ3gOjsbZZRJyD66941sxhhwkSILcMIM0aKJBMnsDLwREwMz8v6lr6gXK8GnWcVRTcMdGo3et7XXyhMA4L3ZOIcnXPMGp5NurmIdQ9U5fw8twAz13Utv8Sr9hsaCjBUa6cgGIxGy66Ob38Sxs9/c5eXCeydjMG+2OouNit6UsM3pVbTDujVC/JVIYRYaRZ5mIDRRHEf1cHW2F98vhSYK7ZQdMqqqq2XzeyvAmwsjwlKhrPR0ZNQL7G1Yw9F6wyoA20=
  file:
  - archive/sous-$TRAVIS_TAG-darwin-10.6.tar.gz
  - archive/sous-$TRAVIS_TAG-linux.tar.gz
  on:
    tags: true
notifications:
  hipchat:
    on_failure: always
    on_success: change
    template: |-
      Travis: %{message}<br />
      %{repository_slug}#%{build_number} (%{branch} : %{author}):<br />
      <a href="%{compare_url}">%{commit_subject}</a><br />
      Build: <a href="%{build_url}">%{build_number}</a>
    format: html
    rooms:
      secure: MYcyZu5zXfvu72SKPt5vdF/LYtzKdybmL0RIIiiTJzGjb08Cz7LyvyfBBkFc9KWxHT3qK/swUUeCxLHYXHDFfzMDiWYPD+QB7Z2704f4/V8Vg3BjGz2CXlnNC3x1ehj3EbryMfg9C2K/dmYXI7YDjvZwT1iGM/63tMBZSUPE25mfnX6CoIpiIqznMB68JmJzTu9k8BxHKVOkwyvzmKKe7bcG+poiurXM60ly2qUqO11gmT019HOQMMUsxqVUXPoSALhZMArqXQzWG7t/408SGByI7CG1RwGuT8h+iGgsDMH4j30quormEG+y+7VzTjetRFae5BPZ0iCIu11p5atFc2ejNbDVGHdagK7H6hCuPzACWtRHDyVV1ZZ6Bv3pAtId1iCXeHebdagMe5BAsAv6G0Li+6WNQL3o7Tj6wSMPeJ/Zz9XwKHeoFocrERMhfCuhyx/M1mPZPYDVFZ/H4/GiNquDppRxUiCWK61XGmQI0fTY+R0mW6pX9l40oELV1kf6PoJCjYPRJI/kXqTi5x6dfLDctKhrUk662iXSailMtaJJKYREa30OvEaXjNrC0OSw+PTmK9zavVtsSkwkgRnBes1ZlYZnH3VKMGM0mV/L/aKzAAY9xsIuUOl8gvHK3NZ/yUWW58ncVqv+++cEM1ZxuFVuVFtIP/EpV5fc0h0/+Wc=


