
coverage:
  status:
    patch:
      default:
        threshold: 5
ignore:
- bin/.*
- *._generated.go
- Makefile
- .travis.yml
- doc/*
- Gemfile
- Gemfile.lock
- Dangerfile
- LICENSE
- README*
- CHANGELOG*
